name: "IMAP Cleaner"
description: "Decodeert IMAP e-mails en stuurt nette tekst naar Home Assistant via MQTT."
version: "1.0.5"
slug: "imap_cleaner"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true

options:
  imap_host: "imap.gmail.com"
  imap_port: 993
  imap_username: ""
  imap_password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "mail/decoded"
  mark_as_read: false

schema:
  imap_host: str
  imap_port: int
  imap_username: str
  imap_password: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
  mark_as_read: bool
